/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.akrap.algobot;

import dev.akrap.algobot.comands.done.DoneCommand;
import dev.akrap.algobot.comands.TodoCommand;
import dev.akrap.algobot.comands.pool.PoolCommand;
import dev.akrap.algobot.comands.review.ReviewCommand;
import picocli.CommandLine;
import picocli.CommandLine.*;

@Command(
        name = "algo",
        description = "백준 알고리즘 문제를 자동 review날짜를 제공하는 CLI입니다",
        mixinStandardHelpOptions = true,
        subcommands = {
                ReviewCommand.class,
                PoolCommand.class,
                DoneCommand.class,
                TodoCommand.class
        }
)
public class App implements Runnable {

    public static void main(String[] args) {
        int exitCode = new CommandLine(new App()).execute(args);
        System.exit(exitCode);
    }

    @Override
    public void run() {
        System.out.println("Try: algo --help");
    }

}
