/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.akrap.algobot;

import dev.akrap.algobot.comands.DoneCommand;
import dev.akrap.algobot.comands.PoolCommand;
import dev.akrap.algobot.comands.ReviewCommand;
import picocli.CommandLine;
import picocli.CommandLine.*;

@Command(
        name = "algo",
        description = "알고리즘 자동 review 설정 CLI 모드입니다",
        mixinStandardHelpOptions = true,
        subcommands = {
                ReviewCommand.class,
                PoolCommand.class,
                DoneCommand.class
        }
)
public class App implements Runnable {

    public static void main(String[] args) {
        int exitCode = new CommandLine(new App()).execute(args);
        System.exit(exitCode);
    }

    @Override
    public void run() {
        System.out.println("Try: algo --help");
    }

}
